version: '3'

services:
  artist:
    container_name: artist-hub
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    command: -c shared_buffers=500MB -c fsync=off
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: "pg_isready"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lito
networks:
  lito:
volumes:
  postgres_data:
    driver: local